variables:
  PROJECT_ID: ${CI_PROJECT_ID}
  ROLE: ${CI_PROJECT_NAME}
  BRANCH: ${CI_COMMIT_REF_NAME}
  TAG: ${CI_COMMIT_TAG}
  PUBLISH: "true"

test:
  trigger:
    project: ecgalaxy/tooling
    strategy: depend
