---
- name: Install cosign
  ansible.builtin.include_tasks: install_cosign.yml
- name: Install dive
  ansible.builtin.include_tasks: install_dive.yml
- name: Install eksctl
  ansible.builtin.include_tasks: install_eksctl.yml
- name: Install helm
  ansible.builtin.include_tasks: install_helm.yml
- name: Install k9s
  ansible.builtin.include_tasks: install_k9s.yml
- name: Install kp
  ansible.builtin.include_tasks: install_kp.yml
- name: Install kubectl
  ansible.builtin.include_tasks: install_kubectl.yml
- name: Install kubeseal
  ansible.builtin.include_tasks: install_kubeseal.yml
- name: Install pack
  ansible.builtin.include_tasks: install_pack.yml
- name: Install skopeo
  ansible.builtin.include_tasks: install_skopeo.yml
  when: (ansible_os_family == 'RedHat' and ansible_distribution != 'Amazon') or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 22)
