---

- name: Install dive
  include: install_dive.yml
- name: Install helm
  include: install_helm.yml
- name: Install k9s
  include: install_k9s.yml
- name: Install kapp
  include: install_kapp.yml
- name: Install kubectl
  include: install_kubectl.yml
- name: Install pack
  include: install_pack.yml
- name: Install ytt
  include: install_ytt.yml
