---
- name: Install dive
  ansible.builtin.include_tasks: install_dive.yml
- name: Install helm
  ansible.builtin.include_tasks: install_helm.yml
- name: Install k9s
  ansible.builtin.include_tasks: install_k9s.yml
- name: Install kapp
  ansible.builtin.include_tasks: install_kapp.yml
- name: Install kubectl
  ansible.builtin.include_tasks: install_kubectl.yml
- name: Install kubeseal
  ansible.builtin.include_tasks: install_kubeseal.yml
- name: Install pack
  ansible.builtin.include_tasks: install_pack.yml
- name: Install ytt
  ansible.builtin.include_tasks: install_ytt.yml
