---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: amazonlinux2-${CI_JOB_ID:-0}
    image: geerlingguy/docker-amazonlinux2-ansible:latest
    pre_build_image: true
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
  - name: centos7-${CI_JOB_ID:-0}
    image: geerlingguy/docker-centos7-ansible:latest
    pre_build_image: true
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
  - name: rockylinux8-${CI_JOB_ID:-0}
    image: geerlingguy/docker-rockylinux8-ansible:latest
    pre_build_image: true
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
  - name: ubuntu1804-${CI_JOB_ID:-0}
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    pre_build_image: true
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
  - name: ubuntu2004-${CI_JOB_ID:-0}
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
  - name: ubuntu2204-${CI_JOB_ID:-0}
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
