---
- name: Check kubectl version
  ansible.builtin.command: kubectl version --client=true --output=json
  register: output
  changed_when: false
- name: Assert that kubectl is installed
  ansible.builtin.assert:
    that:
    - "'{{ kubectl_version }}' in output.stdout"
