---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: verify argocd
      include_tasks: verify_argocd.yml
    - name: verify cosign
      include_tasks: verify_cosign.yml
    - name: verify dive
      include_tasks: verify_dive.yml
    - name: verify eksctl
      include_tasks: verify_eksctl.yml
    - name: verify helm
      include_tasks: verify_helm.yml
    - name: verify k9s
      include_tasks: verify_k9s.yml
    - name: verify kp
      include_tasks: verify_kp.yml
    - name: verify kubectl
      include_tasks: verify_kubectl.yml
    - name: verify kubeseal
      include_tasks: verify_kubeseal.yml
    - name: verify pack
      include_tasks: verify_pack.yml
    - name: verify regctl
      include_tasks: verify_regctl.yml
    - name: verify skopeo
      include_tasks: verify_skopeo.yml
      when: (ansible_os_family == 'RedHat' and ansible_distribution != 'Amazon') or
            (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 22)
