---
- name: Check kubectl version
  ansible.builtin.command: kubectl version --client=true --output=json
  register: output
  changed_when: false
- name: Retrieve kubectl latest version
  ansible.builtin.uri:
    url: "{{ kubectl_version_url }}"
    return_content: true
  register: kubectl_version
- name: debug
  ansible.builtin.debug:
    var: kubectl_version.content
- name: Assert that kubectl is installed
  ansible.builtin.assert:
    that:
    - "'{{ kubectl_version.content }}' in output.stdout"
