---
- name: Check cosign version
  ansible.builtin.command: cosign version
  changed_when: false
  register: output
- name: Assert that cosign is installed
  ansible.builtin.assert:
    that:
    - "'cosign: ' in output.stderr"
    - "'v{{ cosign_version }}' in output.stderr"
